[types]
TRIMESH = "custom"

[node_packs]
ComfyUI-KJNodes = "kijai/ComfyUI-KJNodes"
ComfyUI-VideoHelperSuite = "Kosinkadink/ComfyUI-VideoHelperSuite"
ComfyUI_IPAdapter_plus = "cubiq/ComfyUI_IPAdapter_plus"
ComfyUI_UltimateSDUpscale = "ssitu/ComfyUI_UltimateSDUpscale"